### ISSUE TITLE
Add `default` attribute

### ISSUE THREAD

**Issue by patricoferris** [patricoferris/ppx_deriving_yaml#26]
## Feature Request

Lots of derivers have a `default` attribute. These let you specify that in the absence of the `key` (the key in the example below is `name`) then the `default` value shall be what is supplied in the attribute. 

```ocaml
type t = {
  name : string; [@default "Alice"]
}[@@deriving yaml]
```

`ppx_deriving_yaml` already has a very simplistic version of this for `'a option` types where in their absence `None` is supplied (rather than failing to parse some yaml without that key). A good place to start (thanks @pitag-ha!) would be to how https://github.com/janestreet/ppx_yojson_conv/blob/master/src/ppx_yojson_conv.ml  does it using `Ppxlib.Attributes` https://ocaml-ppx.github.io/ppxlib/ppxlib/Ppxlib/Attribute/index.html

### A concrete example

Consider the yaml:

```yaml
places:
  - name: Belfast
    continent: Europe
```

And the OCaml type that tries to describe it:

```ocaml
type place = {
  name : string;
  continent : string;
  is_city : bool;
} [@@deriving yaml]

type t = {
  places : place list
} [@@deriving yaml]
```

With the current implementation this will fail when trying to parse Belfast's information because there is no key for `is_city`. 

```
Didn't find the function for key: is_city
```

(Output from this example program: https://gist.github.com/patricoferris/4f54f170a7868e27a30c9f6f87b0ec5b)

Most of our places might be cities and so it would be nice to supply a default value. In which case we'd have:

```ocaml
type place = {
  name : string;
  continent : string;
  is_city : bool; [@default true]
} [@@deriving yaml]

type t = {
  places : place list
} [@@deriving yaml]
```

And the program above (with this change) would successfully parse our list of places :)

**Comment by prosper74** [comment]
Please, I will like to try out this issue @patricoferris

**Comment by pitag-ha** [comment]
Hey @prosper74, it's great that you want to work on this! Please go ahead and don't hesitate to ask any question.

**Comment by patricoferris** [comment]
Hi @prosper74, how is it going? Anything I can help with ?

**Comment by prosper74** [comment]
Hi @patricoferris. Thank you for reaching out, I really need the help.
I am yet to get the `@default` functionality working.
I added this code to the [attrs.ml](https://github.com/patricoferris/ppx_deriving_yaml/blob/main/lib/attrs.ml) file
```let default =
  Attribute.declare
    "yaml.default"
    Attribute.Context.label_declaration
    Ast_pattern.(pstr (pstr_eval __ nil ^:: nil))
    (fun x -> x)
```
 I am implementing this right now. I will make a draft PR maybe tomorrow or over the weekend

**Comment by pitag-ha** [comment]
Hey @prosper74, that's already a good observation that you'll need to declare the `default` attribute inside `attrs.ml`. And also the `Ast_pattern` you've chosen for it seems exactly right, which isn't easy!

Once you've declared your attribute in `attr.ml`, you'll also need to expose it in `attr.mli` in order to use the declared attribute somewhere in the code. You usually do that via `Attribute.get`. See for example one place where that's done for the `name` attribute: https://github.com/patricoferris/ppx_deriving_yaml/blob/main/ppx/ppx_deriving_yaml.ml#L48 .

Let us know if you have any questions about that! The issue you've chosen is very interesting, but not very easy.

**Comment by pitag-ha** [comment]
Btw, @patricoferris and @prosper74, just as a side-note: If you want to, you could simplify the `Ast_pattern`s you're constructing:

Concretely, the `Ast_pattern` for `key` and `name`, i.e.
```
Ast_pattern.(pstr (pstr_eval (estring __) nil ^:: nil))
```
should be the same as
```
Ast_pattern.(single_expr_payload (estring __))
```
 And similarly, the `Ast_pattern` that you, @prosper74, have constructed for the `default` attribute and which is absolutely right, i.e.
```
Ast_pattern.(pstr (pstr_eval __ nil ^:: nil))
```
should be the same as
```
Ast_pattern.(single_expr_payload __)
```

Of course, the way you both have chosen to express the `Ast_pattern` works just as well. It would just be a simplification of the same thing.

**Comment by prosper74** [comment]
I really appreciate the help Thank you @patricoferris 🙌 and @pitag-ha 🙌

I have exposed the attribute in the `attrs.mli` file already 

`val default : (label_declaration, expression) Attribute.t`

I will check out the link to see how to use the "default function" in the `ppx_deriving_yaml.ml` file. Hopefully, I will get it done tonight.

**Comment by prosper74** [comment]
hi @patricoferris 

I was trying to clear the commit history as you said. I followed this process 

```
# Check out to a temporary branch:
git checkout --orphan TEMP_BRANCH

# Add all the files:
git add -A

# Commit the changes:
git commit -am "Initial commit"

# Delete the old branch:
git branch -D master

# Rename the temporary branch to master:
git branch -m master

# Finally, force update to our repository:
git push -f origin master
```

but the branch was closed and I can't reopen it from my end. Please, can you reopen it or should I make another PR?

**Comment by patricoferris** [comment]
No worries, feel free to open a new PR

**Comment by prosper74** [comment]
> No worries, feel free to open a new PR

I wasn't able to create a new PR, it was redirecting to the closed PR, so I did ```git reflog``` to checkout the last commit of the deleted branch to a new branch. It worked, but all the commit history came back 😃😃
