### ISSUE TITLE
Separate `to_yaml` and `of_yaml` derivers

### ISSUE THREAD

**Issue by sim642** [patricoferris/ppx_deriving_yaml#33]
It would be nice if one could just derive `to_yaml` or `of_yaml` (with those corresponding deriver names). Then the `yaml` deriver can just be a ppxlib deriver alias for the previous two.

For example, ppx_deriving_yojson registers three derivers: `to_yojson`, `of_yojson` and `yojson`.

**Comment by patricoferris** [comment]
Thanks @sim642 for the suggestion, this would indeed be nice. Hopefully implemented in #36 :))
