### ISSUE TITLE
Omit `[@default]` values in `to_yaml`

### ISSUE THREAD

**Issue by sim642** [patricoferris/ppx_deriving_yaml#35]
The `[@default]` attribute added in #31 is considered in `of_yaml`, but ignored in `to_yaml`. It would be nice, if `to_yaml` would omit fields with their default values. That is how [ppx_deriving_yojson](https://github.com/ocaml-ppx/ppx_deriving_yojson#default) does it at least.

In particular, this would be useful for fields with `option` type and `[@default None]`: `of_yaml` doesn't require the field in input (making it `None`) and the subsequent `to_yaml` wouldn't print out the field with empty value (because it's unnecessary noise for an optional field).

**Comment by maurobringolf** [comment]
Hi there!

I am not yet a user or contributor, but generally interested in ppx and OCaml so I thought I'll give this a shot. I implemented what I think is your proposal and added some thoughts of my own in the PR.

**Comment by patricoferris** [comment]
Fixed in #37 - thanks @maurobringolf!

See the conversation there for ideas of per-field enabling default outputs if people demand it :))
