### ISSUE TITLE
Recursive types are not supported

### ISSUE THREAD

**Issue by zbaylin** [patricoferris/ppx_deriving_yaml#44]
Right now it looks like the serializers and deserializers are defined as `Nonrecursive`: 
https://github.com/patricoferris/ppx_deriving_yaml/blob/0602bc43acbc5b74a94cc6691b5d68db456c2693/src/ppx_deriving_yaml.ml#L178

This means that a type like the following won't work:
```ocaml
type t = {
  name : string;
  children : t list
}
[@@deriving yaml]
```

The compiler produces this error:
```
Unbound value to_yaml
```

(To be clear, I'm not suggesting that simply making the functions recursive will fix this problem, but it's at least part of why this doesn't work. Maybe setting `Nonrecursive` if the type is specifically `nonrec` would fix it?)

**Comment by patricoferris** [comment]
Yep it would, thanks for opening the issue with a really clear explanation! Hopefully fixed in the linked PR :))
